-- Placeholder for 1.12.11 MySQL schema changes
-- No DDL changes required; this version only carries a data migration
-- (re-derive unparseable pipeline task FQNs persisted before double-quote escaping was supported).
