-- Data-only migration: retarget the stale owner terms aggregation field
-- (owners.displayName.keyword -> ownerDisplayName) in stored searchSettings.
-- Handled in org.openmetadata.service.migration.mysql.v1132.Migration. No schema changes.
