# Add here any member that should belong to either a specific team,
# or that can have the tests automatically validated to run safely.

"safe to test":
  - '@ayush-shah'
  - '@TeddyCr'
  - '@ulixius9'
  - '@pmbrull'
  - '@aniketkatkar97'
  - '@Ashish8689'
  - '@chirag-madlani'
  - '@shahsank3t'
  - '@ShaileshParmar11'
  - '@karanh37'
  - '@harshach'
  - '@mohityadav766'
  - '@sureshms'
  - '@akash-jain-10'
  - '@tutte'
  - '@IceS2'
  - '@snyk-bot'
  - '@dependabot'
  - '@harshsoni2024'
  - '@SumanMaharana'
  - '@Prajwal214'
  - '@sonika-shah'
  - '@keshavmohta09'
  - '@sweta1308'
  - '@shrushti2000'
  - '@mohittilala'
  - '@pellejador'
  - '@pranita09'
  - '@edg956'
  - '@manerow'
  - '@miriann-uu'
  - '@github-actions[bot]'

ingestion:
  - '@ayush-shah'
  - '@TeddyCr'
  - '@ulixius9'
  - '@pmbrull'
  - '@IceS2'
  - '@harshsoni2024'
  - '@SumanMaharana'
  - '@keshavmohta09'
  - '@mohittilala'
  - '@edg956'

UI:
  - '@aniketkatkar97'
  - '@Ashish8689'
  - '@chirag-madlani'
  - '@shahsank3t'
  - '@ShaileshParmar11'
  - '@karanh37'
  - '@sweta1308'
  - '@shrushti2000'
  - '@pranita09'

backend:
  - '@harshach'
  - '@mohityadav766'
  - '@sureshms'
  - '@sonika-shah'
  - '@manerow'

devops:
  - '@akash-jain-10'
  - '@tutte'
  - '@pellejador'
  - '@miriann-uu'
