# Add here any member that should belong to either a specific team,
# or that can have the tests automatically validated to run safely.

"safe to test":
  - '@ayush-shah'
  - '@TeddyCr'
  - '@ulixius9'
  - '@pmbrull'
  - '@aniketkatkar97'
  - '@chirag-madlani'
  - '@shahsank3t'
  - '@ShaileshParmar11'
  - '@karanh37'
  - '@harshach'
  - '@mohityadav766'
  - '@sureshms'
  - '@akash-jain-10'
  - '@tutte'
  - '@IceS2'
  - '@snyk-bot'
  - '@dependabot'
  - '@harshsoni2024'
  - '@Prajwal214'
  - '@sonika-shah'
  - '@sweta1308'
  - '@mohittilala'
  - '@pellejador'
  - '@manerow'
  - '@miriann-uu'
  - '@github-actions[bot]'
  - '@Shreyansh100704'
  - '@Vishnuujain'
  - '@lautel'
  - '@tomasmontielp'
  - '@yan-3005'

ingestion:
  - '@ayush-shah'
  - '@TeddyCr'
  - '@ulixius9'
  - '@pmbrull'
  - '@IceS2'
  - '@harshsoni2024'
  - '@mohittilala'

UI:
  - '@aniketkatkar97'
  - '@chirag-madlani'
  - '@shahsank3t'
  - '@ShaileshParmar11'
  - '@karanh37'
  - '@sweta1308'
  - '@siddhant1'
  - '@Rohit0301'
  - '@shrabantipaul-collate'
  - '@harsh-vador'
  - '@anuj-kumary'

backend:
  - '@harshach'
  - '@mohityadav766'
  - '@sureshms'
  - '@sonika-shah'
  - '@manerow'
  - '@yan-3005'

devops:
  - '@akash-jain-10'
  - '@tutte'
  - '@pellejador'
  - '@miriann-uu'
