/*
 *  Copyright 2025 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * Maps category display names to icon component names, derived from
 * the folder structure in Downloads/Icons/. Each icon appears exactly once.
 * The generate-icons.mjs script does NOT overwrite this file.
 */
export const ICON_CATEGORIES: Record<string, string[]> = {
  General: [
    'Articles',
    'Assets',
    'Conversation',
    'CreateFolder',
    'Documents',
    'DownVote',
    'Follow',
    'GridView',
    'ListConversation',
    'ListView',
    'Memories',
    'Owners',
    'Owners1',
    'Pin',
    'RequestUpdateDescription',
    'Teams',
    'TreeView',
    'UpVote',
    'Version',
  ],
  Actions: [
    'AddCharts',
    'ChangePreview',
    'Copy',
    'Delete',
    'Download',
    'Duplicate',
    'Edit',
    'Home',
    'Link',
    'Manage',
    'Restore',
    'Schedule',
    'Share1',
    'Share2',
    'SortBy',
    'Time',
    'Upload',
    'Upload2',
  ],
  Navigation: [
    'ArrowDown',
    'ArrowLeft',
    'ArrowRight',
    'ArrowUp',
    'ChevronDown',
    'ChevronLeft',
    'ChevronRight',
    'ChevronUp',
    'Swap',
  ],
  Profile: [
    'Api',
    'Docs',
    'Help',
    'Language',
    'LogOut',
    'Persona',
    'Persona2',
    'Settings',
    'Tour',
  ],
  'Expand / Collapse': [
    'Collapse',
    'Expand',
    'ListCollapse',
    'ListExpand',
    'MinusCircle',
    'PlusCircle',
  ],
  'Governance — Automation': ['Deploy', 'Kill', 'Logs', 'Run'],
  Observability: [
    'AbortedTests',
    'Accuracy',
    'AddAlert',
    'Completeness',
    'Consistency',
    'DataAssetsCoverage',
    'FailedTests',
    'HealthyDataAssets',
    'Integrity',
    'NoDimension',
    'Sql',
    'SuccessfulTests',
    'TestCaseResults',
    'TotalTests',
    'Uniqueness',
    'Validity',
  ],
  Explore: [
    'Apis',
    'Dashboards',
    'Databases',
    'Drive2',
    'MlModels2',
    'Pipelines2',
    'RankingDetails',
    'Topics2',
  ],
  'AI Studio': [
    'AgentActions',
    'AgentDetails',
    'BehaviorPersonality',
    'EditSkills',
    'PlannerRouting',
    'ToolsCapabilities',
  ],
  'Inbox — My Data': [
    'AssetsOwned',
    'DataHealthScore',
    'OpenIncidents',
    'Queries',
  ],
  'Tasks — DAR': [
    'Approver',
    'AssetsType',
    'Duration',
    'ReasonForAccess',
    'RequestedBy',
    'RequestedOn',
  ],
  'Activity Feed': ['Comment', 'Reactions'],
  'Explore — Right Panel': [
    'CustomProperty',
    'DataContracts',
    'DataQuality',
    'Lineage',
    'Overview',
    'Schema',
  ],
  'Explore — Column Table': ['Customize', 'Sort'],
  'Explore — Activity Feed & Tasks': ['All', 'Tasks'],
  Connectors: ['TotalDataAssets'],
  Services: [
    'ApiService',
    'DashboardService',
    'DataObservability',
    'DatabaseService',
    'DriveService',
    'MessagingService',
    'MetadataService',
    'MlModelService',
    'PipelineService',
    'SearchService',
    'SecurityService',
    'StorageService',
  ],
  'Database & Tables': [
    'Column',
    'Database',
    'DatabaseSchema',
    'Query',
    'StoredProcedure',
    'Table',
  ],
  'Data Quality & Contracts': [
    'DataContract',
    'TestCase',
    'TestCase2',
    'TestDefinition',
    'TestSuite',
  ],
  'Streaming, Storage & Search': ['Container', 'SearchIndex', 'Topic'],
  'Governance & Semantics': [
    'Classification',
    'DataProduct',
    'Domain',
    'Glossary',
    'GlossaryTerm',
    'Tag',
  ],
  'Dashboards & BI': [
    'Chart',
    'Dashboard',
    'DashboardDataModel',
    'Metric',
    'Report',
  ],
  APIs: ['ApiCollection', 'ApiEndpoint'],
  'ML & Pipelines': ['MlModel', 'Pipeline'],
  'Certification Badges': ['Bronze', 'Gold', 'None', 'Silver'],
  'Column Profile': [
    'ColumnCount',
    'CreatedTime',
    'ProfileSampleType',
    'RowCount',
    'RunProfiler',
    'Size',
  ],
  Pipeline: [
    'ActivePipeline',
    'AverageRuntime',
    'Failed',
    'InactivePipeline',
    'TotalPipeline',
  ],
  'Column Bulk Operations': [
    'PendingChanges',
    'TotalOccurrences',
    'TotalUniqueColumn',
  ],
};
