#  Copyright 2025 Collate
#  Licensed under the Collate Community License, Version 1.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/LICENSE
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
"""Generate (or --check) ingestion/SETTINGS.md from the registered OMSettings classes."""

import argparse
import sys
from pathlib import Path

from metadata.config.settings import import_all_settings_modules

_SETTINGS_MD = Path(__file__).resolve().parents[1] / "SETTINGS.md"

_HEADER = (
    "<!-- Generated by ingestion/scripts/generate_settings_docs.py — do not edit by hand. -->\n"
    "# OpenMetadata ingestion settings\n\n"
    "Every OpenMetadata-owned environment variable is `OM_`-prefixed and declared as a "
    "typed field on a registered settings class (`metadata.config.settings`).\n\n"
    "| Variable | Type | Default | Description |\n"
    "|---|---|---|---|\n"
)


def render() -> str:
    """Render the registered settings as a Markdown table sorted by variable name."""
    rows = []
    for cls in import_all_settings_modules().values():
        prefix = cls.model_config.get("env_prefix", "")
        for field_name, field in cls.model_fields.items():
            env = f"{prefix}{field_name}".upper()
            type_name = getattr(field.annotation, "__name__", str(field.annotation))
            description = " ".join((field.description or "").split())
            rows.append((env, type_name, repr(field.default), description))
    rows.sort()
    body = "".join(f"| `{env}` | {typ} | `{default}` | {desc} |\n" for env, typ, default, desc in rows)
    return _HEADER + body


def main() -> int:
    """Write SETTINGS.md, or with --check exit non-zero when it is stale."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if SETTINGS.md is out of date")
    args = parser.parse_args()

    rendered = render()
    result = 0
    if args.check:
        if _SETTINGS_MD.read_text() != rendered:
            print(f"{_SETTINGS_MD} is stale — run: python {Path(__file__).name}")  # noqa: T201
            result = 1
    else:
        _SETTINGS_MD.write_text(rendered)
        print(f"wrote {_SETTINGS_MD}")  # noqa: T201
    return result


if __name__ == "__main__":
    sys.exit(main())
