#!/usr/bin/env python3
"""Summarize OpenMetadata access-log traffic generated by a Playwright shard."""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path
from typing import Iterable


ACCESS_LOG = re.compile(
    r'"(?P<method>GET|POST|PUT|PATCH|DELETE|OPTIONS) '
    r'(?P<path>\S+) HTTP/[^\"]+" (?P<status>\d{3}) (?P<bytes>\S+) '
    r'"[^"]*" "[^"]*" (?P<duration>\d+)'
)
APP_ENTRY = re.compile(r"^/assets/app-[A-Za-z0-9_-]+\.js$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", type=Path, required=True)
    parser.add_argument("--aggregate", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--shard-id", required=True)
    return parser.parse_args()


class RequestAccumulator:
    def __init__(self) -> None:
        self.counters: Counter[str] = Counter()
        self.endpoints: Counter[str] = Counter()
        self.statuses: Counter[str] = Counter()

    def add(self, line: str) -> None:
        match = ACCESS_LOG.search(line)
        if not match:
            return
        path = match["path"].split("?", 1)[0]
        kind = "api" if path.startswith("/api/") else "static"
        response_bytes = match["bytes"]
        self.counters[f"{kind}Requests"] += 1
        self.counters[f"{kind}Bytes"] += (
            0 if response_bytes == "-" else int(response_bytes)
        )
        self.counters[f"{kind}ServerMs"] += int(match["duration"])
        self.statuses[f"{kind}:{match['status']}"] += 1
        if kind == "api":
            self.endpoints[f"{match['method']} {path}"] += 1
        elif APP_ENTRY.match(path):
            self.counters["appBoots"] += 1

    def add_all(self, lines: Iterable[str]) -> None:
        for line in lines:
            self.add(line)

    def payload(self, shard_id: str) -> dict[str, object]:
        return {
            "version": 1,
            "shardId": shard_id,
            "totalRequests": self.counters["apiRequests"]
            + self.counters["staticRequests"],
            **dict(self.counters),
            "statuses": dict(sorted(self.statuses.items())),
            "topApiEndpoints": [
                {"endpoint": endpoint, "requests": requests}
                for endpoint, requests in self.endpoints.most_common(25)
            ],
        }


def main() -> None:
    args = parse_args()
    if args.aggregate and args.aggregate.exists():
        payload = json.loads(args.aggregate.read_text(encoding="utf-8"))
        payload["shardId"] = args.shard_id
    else:
        accumulator = RequestAccumulator()
        if args.log.exists():
            with args.log.open(encoding="utf-8", errors="replace") as lines:
                accumulator.add_all(lines)
        payload = accumulator.payload(args.shard_id)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
