#!/usr/bin/env python3
"""Summarize OpenMetadata access-log traffic generated by a Playwright shard."""

from __future__ import annotations

import argparse
import json
import re
from collections import Counter
from pathlib import Path
from typing import Iterable
from urllib.parse import parse_qs, urlsplit


ACCESS_LOG = re.compile(
    r'"(?P<method>GET|POST|PUT|PATCH|DELETE|OPTIONS) '
    r'(?P<path>\S+) HTTP/[^\"]+" (?P<status>\d{3}) (?P<bytes>\S+) '
    r'"[^"]*" "[^"]*" (?P<duration>\d+)'
)
APP_ENTRY = re.compile(r"^/assets/app-entry-[A-Za-z0-9_-]+\.js$")
STATIC_RESOURCE_SUFFIXES = {
    "css": "stylesheet",
    "gif": "image",
    "ico": "image",
    "jpeg": "image",
    "jpg": "image",
    "js": "javascript",
    "mjs": "javascript",
    "png": "image",
    "svg": "image",
    "webp": "image",
    "woff": "font",
    "woff2": "font",
}


def static_resource_type(path: str) -> str:
    filename = path.rsplit("/", 1)[-1]
    if "." not in filename:
        return "document"
    suffix = filename.rsplit(".", 1)[-1].lower()

    return STATIC_RESOURCE_SUFFIXES.get(suffix, "other")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--log", type=Path, required=True)
    parser.add_argument("--aggregate", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--shard-id", required=True)
    return parser.parse_args()


class RequestAccumulator:
    def __init__(self) -> None:
        self.counters: Counter[str] = Counter()
        self.api_endpoints: Counter[str] = Counter()
        self.static_endpoints: Counter[str] = Counter()
        self.static_resource_types: Counter[str] = Counter()
        self.statuses: Counter[str] = Counter()

    def add(self, line: str) -> None:
        match = ACCESS_LOG.search(line)
        if not match:
            return
        request_url = urlsplit(match["path"])
        path = request_url.path
        if path == "/favicon.ico":
            diagnostics = parse_qs(request_url.query)
            if diagnostics.get("playwright-app-boot") == ["1"]:
                self.counters["appBoots"] += 1
                if diagnostics.get("playwright-ui-scenario") == ["1"]:
                    self.counters["uiScenarios"] += 1
                return
        kind = "api" if path.startswith("/api/") else "static"
        response_bytes = match["bytes"]
        self.counters[f"{kind}Requests"] += 1
        self.counters[f"{kind}Bytes"] += (
            0 if response_bytes == "-" else int(response_bytes)
        )
        self.counters[f"{kind}ServerMs"] += int(match["duration"])
        self.statuses[f"{kind}:{match['status']}"] += 1
        if kind == "api":
            self.api_endpoints[f"{match['method']} {path}"] += 1
        else:
            self.static_endpoints[f"{match['method']} {path}"] += 1
            self.static_resource_types[static_resource_type(path)] += 1
            if APP_ENTRY.match(path):
                self.counters["appEntryRequests"] += 1

    def add_all(self, lines: Iterable[str]) -> None:
        for line in lines:
            self.add(line)

    def payload(self, shard_id: str) -> dict[str, object]:
        return {
            "version": 2,
            "shardId": shard_id,
            "totalRequests": self.counters["apiRequests"]
            + self.counters["staticRequests"],
            **dict(self.counters),
            "statuses": dict(sorted(self.statuses.items())),
            "apiEndpointCounts": dict(sorted(self.api_endpoints.items())),
            "topApiEndpoints": [
                {"endpoint": endpoint, "requests": requests}
                for endpoint, requests in self.api_endpoints.most_common(25)
            ],
            "staticResourceTypes": dict(sorted(self.static_resource_types.items())),
            "staticEndpointCounts": dict(sorted(self.static_endpoints.items())),
            "topStaticEndpoints": [
                {"endpoint": endpoint, "requests": requests}
                for endpoint, requests in self.static_endpoints.most_common(50)
            ],
        }


def main() -> None:
    args = parse_args()
    if args.aggregate and args.aggregate.exists():
        payload = json.loads(args.aggregate.read_text(encoding="utf-8"))
        payload["shardId"] = args.shard_id
    else:
        accumulator = RequestAccumulator()
        if args.log.exists():
            with args.log.open(encoding="utf-8", errors="replace") as lines:
                accumulator.add_all(lines)
        payload = accumulator.payload(args.shard_id)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
