/*
 *  Copyright 2021 Collate
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

package org.openmetadata.service.governance.workflows;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;
import java.util.Locale;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import lombok.extern.slf4j.Slf4j;

/**
 * A {@link Statement} wrapper that makes Flowable DDL upgrade scripts idempotent using
 * standard JDBC {@link DatabaseMetaData} pre-checks. Before executing a CREATE INDEX,
 * CREATE TABLE, or ALTER TABLE ADD COLUMN statement, it checks whether the object
 * already exists and skips execution if so. This allows interrupted Flowable schema
 * upgrades to resume cleanly.
 */
@Slf4j
final class IdempotentDdlStatement implements Statement {

  private static final Pattern CREATE_INDEX_PATTERN =
      Pattern.compile("(?i)create\\s+(?:unique\\s+)?index\\s+(\\S+)\\s+on\\s+(\\S+)\\s*\\(");
  private static final Pattern CREATE_TABLE_PATTERN =
      Pattern.compile("(?i)create\\s+table\\s+(?:if\\s+not\\s+exists\\s+)?(\\S+)\\s*\\(");
  // Negative lookahead prevents matching SQL keywords (CONSTRAINT, PRIMARY, UNIQUE, etc.)
  // as column names when the ADD clause is not a column definition.
  private static final Pattern ALTER_TABLE_ADD_COLUMN_PATTERN =
      Pattern.compile(
          "(?i)alter\\s+table\\s+(\\S+)\\s+add\\s+(?:column\\s+)?"
              + "(?!constraint\\b|primary\\b|unique\\b|foreign\\b|check\\b|index\\b|key\\b)(\\S+)\\s");

  private final Statement delegate;
  private final Connection connection;

  IdempotentDdlStatement(Statement delegate, Connection connection) {
    this.delegate = delegate;
    this.connection = connection;
  }

  private boolean shouldSkip(String sql) throws SQLException {
    Matcher indexMatcher = CREATE_INDEX_PATTERN.matcher(sql);
    if (indexMatcher.find()) {
      String indexName = indexMatcher.group(1).toLowerCase(Locale.ROOT);
      String tableName = indexMatcher.group(2).toLowerCase(Locale.ROOT);
      if (indexExists(indexName, tableName)) {
        LOG.info("Skipping already-existing index: {} on {}", indexName, tableName);
        return true;
      }
      return false;
    }
    Matcher tableMatcher = CREATE_TABLE_PATTERN.matcher(sql);
    if (tableMatcher.find()) {
      String tableName = tableMatcher.group(1).toLowerCase(Locale.ROOT);
      if (tableExists(tableName)) {
        LOG.info("Skipping already-existing table: {}", tableName);
        return true;
      }
      return false;
    }
    Matcher alterMatcher = ALTER_TABLE_ADD_COLUMN_PATTERN.matcher(sql);
    if (alterMatcher.find()) {
      String tableName = alterMatcher.group(1).toLowerCase(Locale.ROOT);
      String columnName = alterMatcher.group(2).toLowerCase(Locale.ROOT);
      if (columnExists(tableName, columnName)) {
        LOG.info("Skipping already-existing column: {}.{}", tableName, columnName);
        return true;
      }
    }
    return false;
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    if (shouldSkip(sql)) return false;
    return delegate.execute(sql);
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    if (shouldSkip(sql)) return false;
    return delegate.execute(sql, autoGeneratedKeys);
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    if (shouldSkip(sql)) return false;
    return delegate.execute(sql, columnIndexes);
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    if (shouldSkip(sql)) return false;
    return delegate.execute(sql, columnNames);
  }

  private boolean indexExists(String indexName, String tableName) throws SQLException {
    DatabaseMetaData meta = connection.getMetaData();
    try (ResultSet rs = meta.getIndexInfo(null, null, tableName, false, false)) {
      while (rs.next()) {
        if (indexName.equalsIgnoreCase(rs.getString("INDEX_NAME"))) {
          return true;
        }
      }
    }
    return false;
  }

  private boolean tableExists(String tableName) throws SQLException {
    DatabaseMetaData meta = connection.getMetaData();
    try (ResultSet rs = meta.getTables(null, null, tableName, null)) {
      return rs.next();
    }
  }

  private boolean columnExists(String tableName, String columnName) throws SQLException {
    DatabaseMetaData meta = connection.getMetaData();
    try (ResultSet rs = meta.getColumns(null, null, tableName, columnName)) {
      return rs.next();
    }
  }

  // All remaining Statement methods delegate to the underlying statement.

  @Override
  public java.sql.ResultSet executeQuery(String sql) throws SQLException {
    return delegate.executeQuery(sql);
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    if (shouldSkip(sql)) return 0;
    return delegate.executeUpdate(sql);
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    if (shouldSkip(sql)) return 0;
    return delegate.executeUpdate(sql, autoGeneratedKeys);
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    if (shouldSkip(sql)) return 0;
    return delegate.executeUpdate(sql, columnIndexes);
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    if (shouldSkip(sql)) return 0;
    return delegate.executeUpdate(sql, columnNames);
  }

  @Override
  public void close() throws SQLException {
    delegate.close();
  }

  @Override
  public int getMaxFieldSize() throws SQLException {
    return delegate.getMaxFieldSize();
  }

  @Override
  public void setMaxFieldSize(int max) throws SQLException {
    delegate.setMaxFieldSize(max);
  }

  @Override
  public int getMaxRows() throws SQLException {
    return delegate.getMaxRows();
  }

  @Override
  public void setMaxRows(int max) throws SQLException {
    delegate.setMaxRows(max);
  }

  @Override
  public void setEscapeProcessing(boolean enable) throws SQLException {
    delegate.setEscapeProcessing(enable);
  }

  @Override
  public int getQueryTimeout() throws SQLException {
    return delegate.getQueryTimeout();
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    delegate.setQueryTimeout(seconds);
  }

  @Override
  public void cancel() throws SQLException {
    delegate.cancel();
  }

  @Override
  public SQLWarning getWarnings() throws SQLException {
    return delegate.getWarnings();
  }

  @Override
  public void clearWarnings() throws SQLException {
    delegate.clearWarnings();
  }

  @Override
  public void setCursorName(String name) throws SQLException {
    delegate.setCursorName(name);
  }

  @Override
  public java.sql.ResultSet getResultSet() throws SQLException {
    return delegate.getResultSet();
  }

  @Override
  public int getUpdateCount() throws SQLException {
    return delegate.getUpdateCount();
  }

  @Override
  public boolean getMoreResults() throws SQLException {
    return delegate.getMoreResults();
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    delegate.setFetchDirection(direction);
  }

  @Override
  public int getFetchDirection() throws SQLException {
    return delegate.getFetchDirection();
  }

  @Override
  public void setFetchSize(int rows) throws SQLException {
    delegate.setFetchSize(rows);
  }

  @Override
  public int getFetchSize() throws SQLException {
    return delegate.getFetchSize();
  }

  @Override
  public int getResultSetConcurrency() throws SQLException {
    return delegate.getResultSetConcurrency();
  }

  @Override
  public int getResultSetType() throws SQLException {
    return delegate.getResultSetType();
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    delegate.addBatch(sql);
  }

  @Override
  public void clearBatch() throws SQLException {
    delegate.clearBatch();
  }

  @Override
  public int[] executeBatch() throws SQLException {
    return delegate.executeBatch();
  }

  @Override
  public Connection getConnection() throws SQLException {
    return delegate.getConnection();
  }

  @Override
  public boolean getMoreResults(int current) throws SQLException {
    return delegate.getMoreResults(current);
  }

  @Override
  public java.sql.ResultSet getGeneratedKeys() throws SQLException {
    return delegate.getGeneratedKeys();
  }

  @Override
  public int getResultSetHoldability() throws SQLException {
    return delegate.getResultSetHoldability();
  }

  @Override
  public boolean isClosed() throws SQLException {
    return delegate.isClosed();
  }

  @Override
  public void setPoolable(boolean poolable) throws SQLException {
    delegate.setPoolable(poolable);
  }

  @Override
  public boolean isPoolable() throws SQLException {
    return delegate.isPoolable();
  }

  @Override
  public void closeOnCompletion() throws SQLException {
    delegate.closeOnCompletion();
  }

  @Override
  public boolean isCloseOnCompletion() throws SQLException {
    return delegate.isCloseOnCompletion();
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    return delegate.unwrap(iface);
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) throws SQLException {
    return delegate.isWrapperFor(iface);
  }
}
