from qlik_sdk import Apps, AuthType, Config
base_url = "https://rpeh4a1kk8uzpoo.sg.qlikcloud.com/"
api_key  = "eyJhbGciOiJFUzM4NCIsImtpZCI6IjUyOTA0MDdkLTVkNWYtNGZhNC04MjliLWQxM2MwZjQ4ZDJhNSIsInR5cCI6IkpXVCJ9.eyJzdWJUeXBlIjoidXNlciIsInRlbmFudElkIjoiZUxkemZVdmtuNUtvM1dpT2ZYbUoxMG4zSk5aUmszNlYiLCJqdGkiOiI1MjkwNDA3ZC01ZDVmLTRmYTQtODI5Yi1kMTNjMGY0OGQyYTUiLCJhdWQiOiJxbGlrLmFwaSIsImlzcyI6InFsaWsuYXBpL2FwaS1rZXlzIiwic3ViIjoiNjQ3MDJhYjZhODU1YTdhNTk3MzQ3ZDQ3In0.LyR1tYegAGQkv47avDRKCYM6conrcBA_ZkmvGFC9CFVvr0zPxJsD3zGbnNjHvCesLp8FCBoAHWmGBZSibknExvfVQuF8Nf2foyFd5nhrox6RZ5J86CtWqZy0-u4sKsbt"

config = Config(host=base_url, auth_type=AuthType.APIKey, api_key=api_key)
apps = Apps(config)

print("hellow")


