name: Setup OpenMetadata Test Environment
description: Steps needed to have a coherent test environment

inputs:
  python-version:
    description: Python Version to install
    required: true
  java-version:
    description: Java Version to install
    default: '21'
  npm-version:
    description: NPM Version to install
    default: 'v22.x'
  args:
    description: Arguments to pass to run_local_docker.sh
    required: false
    default: "-m no-ui -d mysql"  # Use "-d postgresql" for postgres and Opensearch
  ingestion_dependency:
    description: Ingestion dependency to pass to run_local_docker.sh
    required: false
    default: "mysql,elasticsearch,sample-data"

runs:
  using: composite
  steps:
    # ---- Install Ubuntu Dependencies ---------------------------------------------
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y -qq unixodbc-dev librdkafka-dev gcc libsasl2-dev \
        build-essential libssl-dev libffi-dev libevent-dev python3-dev libkrb5-dev tdsodbc \
        libmysqlclient-dev pkg-config curl unzip make jq && ACCEPT_EULA=Y sudo apt-get -qq install -y msodbcsql18
      shell: bash
    # ------------------------------------------------------------------------------

    # ---- Setup Java --------------------------------------------------------------
    - name: Setup JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
    # ------------------------------------------------------------------------------

    # ---- Setup Node --------------------------------------------------------------
    - name: Use Node.js ${{ inputs.npm-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.npm-version }}

    - name: Install yarn
      run: npm install -g yarn
      shell: bash
    # ------------------------------------------------------------------------------

    # ---- Setup Python Test Environment -------------------------------------------
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Setup Python Environment and Generate Models
      run: |
        cd ingestion
        sudo make -C .. install_antlr_cli
        make -C .. generate
      shell: bash

    - name: Install All Python Dependencies
      run: |
        cd ingestion
        # Use uv sync with frozen lock file for reproducible builds
        make uv_sync_frozen
      shell: bash
    # ------------------------------------------------------------------------------

    # ---- Start OpenMetadata Server and ingest Sample Data ------------------------
    - name: Start Server and Ingest Sample Data
      uses: nick-fields/retry@v3.0.2
      env:
        INGESTION_DEPENDENCY: ${{ inputs.ingestion_dependency }}
        # Ensure the Docker script uses the uv-managed virtual environment
        VIRTUAL_ENV: ${{ github.workspace }}/ingestion/.venv
        PATH: ${{ github.workspace }}/ingestion/.venv/bin:${{ env.PATH }}
      with:
        timeout_minutes: 60
        max_attempts: 2
        retry_on: error
        command: ./docker/run_local_docker.sh ${{ inputs.args }}
