CREATE INDEX apps_extension_time_series_timestamp ON apps_extension_time_series("timestamp");
CREATE INDEX workflow_instance_time_series_timestamp ON workflow_instance_time_series("timestamp");
CREATE INDEX workflow_instance_state_time_series_timestamp ON workflow_instance_state_time_series("timestamp");