#!/usr/bin/env node
/**
 * Sweep ledger for the antd → ui-core-components migration.
 *
 *   node ledger.mjs \
 *     --repo openmetadata-ui=/abs/path/to/openmetadata-ui/src/main/resources/ui \
 *     --repo collate-ui=/abs/path/to/collate-ui/src/main/resources/ui \
 *     --repo collate-local-webserver=/abs/path/to/collate-local-webserver/ui \
 *     --out /abs/path/to/LEDGER.md
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SKIP_DIRS = new Set(['node_modules', 'dist', 'build', 'target', '.git', 'generated', 'openmetadata-ui']); // collate-ui vendors the upstream UI here (gitignored build artifact)
// Owned by open-metadata/OpenMetadata#29849 — QueryBuilder has its own migration PR.
const EXCLUDED = [/QueryBuilder/i];
const CODE_EXT = /\.(ts|tsx|js|jsx)$/;
const STYLE_EXT = /\.(less|css|scss)$/;

export function parseAntdImports(source) {
  const found = [];
  const named =
    /import\s+(?:type\s+)?(?:[A-Za-z0-9_$]+\s*,\s*)?\{([^}]+)\}\s+from\s+['"]antd['"]/gs;
  for (const m of source.matchAll(named)) {
    for (const raw of m[1].split(',')) {
      const name = raw.trim().split(/\s+as\s+/)[0].trim();
      if (name) found.push(name);
    }
  }
  const subpath = /import\s+[^;]*?from\s+['"](antd\/[^'"]+)['"]/g;
  for (const m of source.matchAll(subpath)) {
    found.push(m[1]);
  }
  return found;
}

export function countAntSelectors(source) {
  return (source.match(/\.ant-[a-z0-9-]+/g) ?? []).length;
}

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    if (SKIP_DIRS.has(entry)) continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) yield* walk(full);
    else yield full;
  }
}

function scanRepo(root) {
  const perComponent = new Map();
  let antSelectors = 0;
  let excludedFiles = 0;
  const srcRoot = join(root, 'src');
  for (const file of walk(srcRoot)) {
    if (EXCLUDED.some((re) => re.test(file))) {
      excludedFiles += 1;
      continue;
    }
    if (CODE_EXT.test(file)) {
      for (const name of parseAntdImports(readFileSync(file, 'utf8'))) {
        perComponent.set(name, (perComponent.get(name) ?? 0) + 1);
      }
    }
    if (STYLE_EXT.test(file) || CODE_EXT.test(file)) {
      antSelectors += countAntSelectors(readFileSync(file, 'utf8'));
    }
  }
  return { perComponent, antSelectors, excludedFiles };
}

function renderMarkdown(results) {
  const repos = [...results.keys()];
  const components = new Set();
  for (const { perComponent } of results.values()) {
    for (const name of perComponent.keys()) components.add(name);
  }
  const rows = [...components].sort((a, b) => {
    const total = (n) =>
      repos.reduce((s, r) => s + (results.get(r).perComponent.get(n) ?? 0), 0);
    return total(b) - total(a);
  });
  const lines = [];
  lines.push('# AntD migration sweep ledger');
  lines.push('');
  lines.push('Generated by `tooling/antd-migration/ledger.mjs` — do not edit by hand.');
  lines.push('');
  lines.push(`| Component | ${repos.join(' | ')} |`);
  lines.push(`|---|${repos.map(() => '---|').join('')}`);
  for (const name of rows) {
    const cells = repos.map((r) => results.get(r).perComponent.get(name) ?? 0);
    lines.push(`| \`${name}\` | ${cells.join(' | ')} |`);
  }
  lines.push('');
  lines.push(`| CSS / meta | ${repos.join(' | ')} |`);
  lines.push(`|---|${repos.map(() => '---|').join('')}`);
  lines.push(
    `| \`.ant-*\` selector occurrences | ${repos
      .map((r) => results.get(r).antSelectors)
      .join(' | ')} |`
  );
  lines.push(
    `| files excluded (QueryBuilder, PR #29849) | ${repos
      .map((r) => results.get(r).excludedFiles)
      .join(' | ')} |`
  );
  lines.push('');
  return lines.join('\n');
}

const isMain = process.argv[1]?.endsWith('ledger.mjs');
if (isMain) {
  const repoArgs = [];
  let out = null;
  const argv = process.argv.slice(2);
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--repo') repoArgs.push(argv[(i += 1)]);
    if (argv[i] === '--out') out = argv[(i += 1)];
  }
  if (!repoArgs.length || !out) {
    console.error('Usage: node ledger.mjs --repo name=path [--repo …] --out file.md');
    process.exit(1);
  }
  const results = new Map();
  for (const arg of repoArgs) {
    const [name, root] = arg.split('=');
    results.set(name, scanRepo(root));
  }
  writeFileSync(out, renderMarkdown(results));
  console.log(`ledger written to ${out}`);
}
