/*
 *  Copyright 2022 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

export enum EntityType {
  TABLE = 'table',
  TOPIC = 'topic',
  CLASSIFICATION = 'classification',
  DASHBOARD = 'dashboard',
  PIPELINE = 'pipeline',
  DATABASE = 'database',
  DATABASE_SCHEMA = 'databaseSchema',
  GLOSSARY = 'glossary',
  GLOSSARY_TERM = 'glossaryTerm',
  DATABASE_SERVICE = 'databaseService',
  MESSAGING_SERVICE = 'messagingService',
  METADATA_SERVICE = 'metadataService',
  DASHBOARD_SERVICE = 'dashboardService',
  PIPELINE_SERVICE = 'pipelineService',
  MLMODEL_SERVICE = 'mlmodelService',
  STORAGE_SERVICE = 'storageService',
  SEARCH_SERVICE = 'searchService',
  SECURITY_SERVICE = 'securityService',
  WEBHOOK = 'webhook',
  MLMODEL = 'mlmodel',
  TYPE = 'type',
  TEAM = 'team',
  USER = 'user',
  BOT = 'bot',
  ROLE = 'role',
  POLICY = 'policy',
  TEST_SUITE = 'testSuite',
  TEST_CASE = 'testCase',
  DATA_INSIGHT_CHART = 'dataInsightChart',
  KPI = 'kpi',
  ALERT = 'alert',
  CONTAINER = 'container',
  TAG = 'tag',
  DASHBOARD_DATA_MODEL = 'dashboardDataModel',
  SUBSCRIPTION = 'subscription',
  CHART = 'chart',
  DOMAIN = 'domain',
  DATA_PRODUCT = 'dataProduct',
  SAMPLE_DATA = 'sampleData',
  STORED_PROCEDURE = 'storedProcedure',
  SEARCH_INDEX = 'searchIndex',
  APP_MARKET_PLACE_DEFINITION = 'appMarketPlaceDefinition',
  APPLICATION = 'app',
  PERSONA = 'persona',
  DOC_STORE = 'docStore',
  PAGE = 'Page',
  KNOWLEDGE_PAGE = 'page',
  knowledgePanels = 'KnowLedgePanels',
  GOVERN = 'govern',
  ALL = 'all',
  CUSTOM_METRIC = 'customMetric',
  INGESTION_PIPELINE = 'ingestionPipeline',
  QUERY = 'query',
  ENTITY_REPORT_DATA = 'entityReportData',
  WEB_ANALYTIC_ENTITY_VIEW_REPORT_DATA = 'webAnalyticEntityViewReportData',
  WEB_ANALYTIC_USER_ACTIVITY_REPORT_DATA = 'webAnalyticUserActivityReportData',
  TEST_CASE_RESOLUTION_STATUS = 'test_case_resolution_status_search_index',
  TEST_CASE_RESULT = 'test_case_result_search_index',
  EVENT_SUBSCRIPTION = 'eventsubscription',
  LINEAGE_EDGE = 'lineageEdge',
  API_SERVICE = 'apiService',
  API_COLLECTION = 'apiCollection',
  API_ENDPOINT = 'apiEndpoint',
  METRIC = 'metric',
  WORKFLOW_DEFINITION = 'workflowDefinition',
  SERVICE = 'service',
  DATA_CONTRACT = 'dataContract',
  INGESTION_RUNNER = 'ingestionRunner',
}

export enum EntityLineageDirection {
  TOP_BOTTOM = 'TB',
  LEFT_RIGHT = 'LR',
}

export enum EntityLineageNodeType {
  INPUT = 'input',
  OUTPUT = 'output',
  DEFAULT = 'default',
  NOT_CONNECTED = 'not-connected',
  LOAD_MORE = 'load-more',
}

export enum TabSpecificField {
  ACTIVITY_FEED = 'activity_feed',
  ASSETS = 'assets',
  CHARTS = 'charts',
  CHILDREN = 'children',
  CHILDREN_COUNT = 'childrenCount',
  COLUMNS = 'columns',
  CUSTOM_METRICS = 'customMetrics',
  CUSTOM_PROPERTIES = 'customProperties',
  DASHBOARD = 'dashboard',
  DATAMODEL = 'dataModel',
  DATA_INSIGHT_CHART = 'dataInsightChart',
  DATA_PRODUCTS = 'dataProducts',
  DEFAULT_PERSONA = 'defaultPersona',
  DEFAULT_ROLES = 'defaultRoles',
  DOMAIN = 'domain',
  DOMAINS = 'domains',
  END_DATE = 'endDate',
  EXECUTIONS = 'executions',
  EXPERTS = 'experts',
  EXTENSION = 'extension',
  FIELDS = 'fields',
  FOLLOWERS = 'followers',
  FOLLOWS = 'follows',
  INCIDENT_ID = 'incidentId',
  JOINS = 'joins',
  LAST_ACTIVITY_TIME = 'lastActivityTime',
  LAST_LOGIN_TIME = 'lastLoginTime',
  LINEAGE = 'lineage',
  LOCATION = 'location',
  METRIC_TYPE = 'metricType',
  OWNERS = 'owners',
  OWNS = 'owns',
  PARENT = 'parent',
  PARENTS = 'parents',
  PERSONAS = 'personas',
  PERSONA_PREFERENCES = 'personaPreferences',
  PIPELINES = 'pipelines',
  PIPELINE_STATUS = 'pipelineStatus',
  PIPELINE_STATUSES = 'pipelineStatuses',
  POLICIES = 'policies',
  PROFILE = 'profile',
  QUERY_USED_IN = 'queryUsedIn',
  RELATED_METRICS = 'relatedMetrics',
  RELATED_TERMS = 'relatedTerms',
  REVIEWERS = 'reviewers',
  ROLES = 'roles',
  SAMPLE_DATA = 'sampleData',
  SCHEDULE_INTERVAL = 'scheduleInterval',
  SCHEMA_DEFINITION = 'schemaDefinition',
  START_DATE = 'startDate',
  STATE = 'state',
  SUMMARY = 'summary',
  TABLE_CONSTRAINTS = 'tableConstraints',
  TABLE_PROFILE = 'profile',
  TABLE_QUERIES = 'tableQueries',
  TAGS = 'tags',
  TARGET_DEFINITION = 'targetDefinition',
  TARGET_VALUE = 'targetValue',
  TASKS = 'tasks',
  TEAMS = 'teams',
  TERM_COUNT = 'termCount',
  TESTS = 'tests',
  TESTSUITE = 'testSuite',
  TEST_CASE_RESULT = 'testCaseResult',
  TEST_DEFINITION = 'testDefinition',
  UI_CUSTOMIZATION = 'uiCustomization',
  USAGE_COUNT = 'usageCount',
  USAGE_SUMMARY = 'usageSummary',
  USERS = 'users',
  USER_COUNT = 'userCount',
  VIEW_DEFINITION = 'viewDefinition',
  VOTES = 'votes',
}

export enum FqnPart {
  Service,
  Database,
  Schema,
  Table,
  Column,
  NestedColumn,
  Topic,
  SearchIndexField,
  TestCase,
  ApiEndpoint,
}

export enum EntityTabs {
  SCHEMA = 'schema',
  SCHEMAS = 'schemas',
  ACTIVITY_FEED = 'activity_feed',
  SAMPLE_DATA = 'sample_data',
  TABLE_QUERIES = 'table_queries',
  PROFILER = 'profiler',
  LINEAGE = 'lineage',
  DBT = 'dbt',
  VIEW_DEFINITION = 'view_definition',
  SCHEMA_DEFINITION = 'schema_definition',
  CUSTOM_PROPERTIES = 'custom_properties',
  MODEL = 'model',
  FEATURES = 'features',
  TASKS = 'tasks',
  CONFIG = 'config',
  DETAILS = 'details',
  CHILDREN = 'children',
  EXECUTIONS = 'executions',
  TABLE = 'table',
  TEST_CASES = 'test-cases',
  PIPELINE = 'pipeline',
  DATA_Model = 'data-model',
  AGENTS = 'agents',
  CONNECTION = 'connection',
  SQL = 'sql',
  FIELDS = 'fields',
  SEARCH_INDEX_SETTINGS = 'search-index-settings',
  STORED_PROCEDURE = 'stored_procedure',
  CODE = 'code',
  API_COLLECTION = 'apiCollection',
  API_ENDPOINT = 'apiEndpoint',
  OVERVIEW = 'overview',
  INCIDENTS = 'incidents',
  TERMS = 'terms',
  GLOSSARY_TERMS = 'glossary_terms',
  ASSETS = 'assets',
  EXPRESSION = 'expression',
  INSIGHTS = 'insights',
  DASHBOARD = 'dashboard',
  DOCUMENTATION = 'documentation',
  DATA_PRODUCTS = 'data_products',
  SUBDOMAINS = 'subdomains',
  CONTRACT = 'contract',
}

export enum EntityAction {
  EXPORT = 'export',
  IMPORT = 'import',
}
