/*
 *  Copyright 2022 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

export enum SearchIndex {
  ALL = 'all',
  DATA_ASSET = 'dataAsset',
  TABLE = 'table',
  TOPIC = 'topic',
  CHART = 'chart',
  DASHBOARD = 'dashboard',
  PIPELINE = 'pipeline',
  USER = 'user',
  TEAM = 'team',
  GLOSSARY = 'glossary',
  GLOSSARY_TERM = 'glossaryTerm',
  MLMODEL = 'mlmodel',
  TAG = 'tag',
  CONTAINER = 'container',
  QUERY = 'query',
  TEST_CASE = 'testCase',
  TEST_SUITE = 'testSuite',
  DATABASE_SCHEMA = 'databaseSchema',
  DATABASE = 'database',
  DATABASE_SERVICE = 'databaseService',
  MESSAGING_SERVICE = 'messagingService',
  PIPELINE_SERVICE = 'pipelineService',
  SEARCH_SERVICE = 'searchService',
  DASHBOARD_SERVICE = 'dashboardService',
  ML_MODEL_SERVICE = 'mlModelService',
  STORAGE_SERVICE = 'storageService',
  DRIVE_SERVICE = 'driveService',
  DOMAIN = 'domain',
  SEARCH_INDEX = 'searchIndex',
  STORED_PROCEDURE = 'storedProcedure',
  DASHBOARD_DATA_MODEL = 'dashboardDataModel',
  DATA_PRODUCT = 'dataProduct',
  INGESTION_PIPELINE = 'ingestionPipeline',
  API_SERVICE_INDEX = 'apiService',
  API_COLLECTION_INDEX = 'apiCollection',
  API_ENDPOINT_INDEX = 'apiEndpoint',
  METRIC_SEARCH_INDEX = 'metric',
  SERVICE = 'service',
  DIRECTORY_SEARCH_INDEX = 'directory',
  FILE_SEARCH_INDEX = 'file',
  SPREADSHEET_SEARCH_INDEX = 'spreadsheet',
  WORKSHEET_SEARCH_INDEX = 'worksheet',
}

export const SEARCH_INDEX_PHYSICAL_NAME: Partial<Record<SearchIndex, string>> =
  {
    [SearchIndex.TABLE]: 'table_search_index',
    [SearchIndex.TOPIC]: 'topic_search_index',
    [SearchIndex.CHART]: 'chart_search_index',
    [SearchIndex.DASHBOARD]: 'dashboard_search_index',
    [SearchIndex.PIPELINE]: 'pipeline_search_index',
    [SearchIndex.USER]: 'user_search_index',
    [SearchIndex.TEAM]: 'team_search_index',
    [SearchIndex.GLOSSARY]: 'glossary_search_index',
    [SearchIndex.GLOSSARY_TERM]: 'glossary_term_search_index',
    [SearchIndex.MLMODEL]: 'mlmodel_search_index',
    [SearchIndex.TAG]: 'tag_search_index',
    [SearchIndex.CONTAINER]: 'container_search_index',
    [SearchIndex.QUERY]: 'query_search_index',
    [SearchIndex.TEST_CASE]: 'test_case_search_index',
    [SearchIndex.TEST_SUITE]: 'test_suite_search_index',
    [SearchIndex.DATABASE_SCHEMA]: 'database_schema_search_index',
    [SearchIndex.DATABASE]: 'database_search_index',
    [SearchIndex.DATABASE_SERVICE]: 'database_service_search_index',
    [SearchIndex.MESSAGING_SERVICE]: 'messaging_service_search_index',
    [SearchIndex.PIPELINE_SERVICE]: 'pipeline_service_search_index',
    [SearchIndex.SEARCH_SERVICE]: 'search_service_search_index',
    [SearchIndex.DASHBOARD_SERVICE]: 'dashboard_service_search_index',
    [SearchIndex.ML_MODEL_SERVICE]: 'mlmodel_service_search_index',
    [SearchIndex.STORAGE_SERVICE]: 'storage_service_search_index',
    [SearchIndex.DRIVE_SERVICE]: 'drive_service_search_index',
    [SearchIndex.DOMAIN]: 'domain_search_index',
    [SearchIndex.SEARCH_INDEX]: 'search_entity_search_index',
    [SearchIndex.STORED_PROCEDURE]: 'stored_procedure_search_index',
    [SearchIndex.DASHBOARD_DATA_MODEL]: 'dashboard_data_model_search_index',
    [SearchIndex.DATA_PRODUCT]: 'data_product_search_index',
    [SearchIndex.INGESTION_PIPELINE]: 'ingestion_pipeline_search_index',
    [SearchIndex.API_SERVICE_INDEX]: 'api_service_search_index',
    [SearchIndex.API_COLLECTION_INDEX]: 'api_collection_search_index',
    [SearchIndex.API_ENDPOINT_INDEX]: 'api_endpoint_search_index',
    [SearchIndex.METRIC_SEARCH_INDEX]: 'metric_search_index',
    [SearchIndex.DIRECTORY_SEARCH_INDEX]: 'directory_search_index',
    [SearchIndex.FILE_SEARCH_INDEX]: 'file_search_index',
    [SearchIndex.SPREADSHEET_SEARCH_INDEX]: 'spreadsheet_search_index',
    [SearchIndex.WORKSHEET_SEARCH_INDEX]: 'worksheet_search_index',
  };
