apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cronomjobs.pipelines.openmetadata.org
spec:
  group: pipelines.openmetadata.org
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              schedule:
                type: string
                description: Cron schedule expression
              timeZone:
                type: string
                description: Time zone for the schedule (default UTC)
              suspend:
                type: boolean
                description: Whether to suspend scheduling
              startingDeadlineSeconds:
                type: integer
                description: Deadline for starting the job if missed
              successfulJobsHistoryLimit:
                type: integer
                description: Number of successful jobs to keep
              failedJobsHistoryLimit:
                type: integer
                description: Number of failed jobs to keep
              omJobSpec:
                type: object
                description: OMJob template to create
                properties:
                  mainPodSpec:
                    type: object
                    properties:
                      image:
                        type: string
                        description: Container image for the main pod
                      imagePullPolicy:
                        type: string
                        description: Image pull policy
                      imagePullSecrets:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                        description: List of image pull secrets
                      serviceAccountName:
                        type: string
                        description: Service account to use
                      command:
                        type: array
                        items:
                          type: string
                        description: Command to run in the container
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the environment variable
                            value:
                              type: string
                              description: Direct value of the environment variable
                            valueFrom:
                              type: object
                              description: Source for the environment variable value
                              properties:
                                configMapKeyRef:
                                  type: object
                                  description: Reference to a key in a ConfigMap
                                  properties:
                                    name:
                                      type: string
                                      description: Name of the ConfigMap
                                    key:
                                      type: string
                                      description: Key in the ConfigMap
                                    optional:
                                      type: boolean
                                      description: Whether the ConfigMap must exist
                                  required:
                                  - name
                                  - key
                                secretKeyRef:
                                  type: object
                                  description: Reference to a key in a Secret
                                  properties:
                                    name:
                                      type: string
                                      description: Name of the Secret
                                    key:
                                      type: string
                                      description: Key in the Secret
                                    optional:
                                      type: boolean
                                      description: Whether the Secret must exist
                                  required:
                                  - name
                                  - key
                                fieldRef:
                                  type: object
                                  description: Reference to a field in the pod
                                  properties:
                                    apiVersion:
                                      type: string
                                      description: API version of the field reference
                                    fieldPath:
                                      type: string
                                      description: Path to the field
                                  required:
                                  - fieldPath
                                resourceFieldRef:
                                  type: object
                                  description: Reference to a resource field
                                  properties:
                                    containerName:
                                      type: string
                                      description: Name of the container
                                    resource:
                                      type: string
                                      description: Resource to select
                                    divisor:
                                      type: string
                                      description: Divisor for the resource
                                  required:
                                  - resource
                          required:
                          - name
                        description: Environment variables for the container
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            additionalProperties:
                              type: string
                          limits:
                            type: object
                            additionalProperties:
                              type: string
                        description: Resource requirements
                      nodeSelector:
                        type: object
                        additionalProperties:
                          type: string
                        description: Node selector for pod placement
                      securityContext:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        description: Pod security context
                      labels:
                        type: object
                        additionalProperties:
                          type: string
                        description: Labels for the pod
                      annotations:
                        type: object
                        additionalProperties:
                          type: string
                        description: Annotations for the pod
                    required:
                    - image
                  exitHandlerSpec:
                    type: object
                    properties:
                      image:
                        type: string
                        description: Container image for the exit handler pod
                      imagePullPolicy:
                        type: string
                        description: Image pull policy
                      imagePullSecrets:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                        description: List of image pull secrets
                      serviceAccountName:
                        type: string
                        description: Service account to use
                      command:
                        type: array
                        items:
                          type: string
                        description: Command to run in the container
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                              description: Name of the environment variable
                            value:
                              type: string
                              description: Direct value of the environment variable
                            valueFrom:
                              type: object
                              description: Source for the environment variable value
                              properties:
                                configMapKeyRef:
                                  type: object
                                  description: Reference to a key in a ConfigMap
                                  properties:
                                    name:
                                      type: string
                                      description: Name of the ConfigMap
                                    key:
                                      type: string
                                      description: Key in the ConfigMap
                                    optional:
                                      type: boolean
                                      description: Whether the ConfigMap must exist
                                  required:
                                  - name
                                  - key
                                secretKeyRef:
                                  type: object
                                  description: Reference to a key in a Secret
                                  properties:
                                    name:
                                      type: string
                                      description: Name of the Secret
                                    key:
                                      type: string
                                      description: Key in the Secret
                                    optional:
                                      type: boolean
                                      description: Whether the Secret must exist
                                  required:
                                  - name
                                  - key
                                fieldRef:
                                  type: object
                                  description: Reference to a field in the pod
                                  properties:
                                    apiVersion:
                                      type: string
                                      description: API version of the field reference
                                    fieldPath:
                                      type: string
                                      description: Path to the field
                                  required:
                                  - fieldPath
                                resourceFieldRef:
                                  type: object
                                  description: Reference to a resource field
                                  properties:
                                    containerName:
                                      type: string
                                      description: Name of the container
                                    resource:
                                      type: string
                                      description: Resource to select
                                    divisor:
                                      type: string
                                      description: Divisor for the resource
                                  required:
                                  - resource
                          required:
                          - name
                        description: Environment variables for the container
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            additionalProperties:
                              type: string
                          limits:
                            type: object
                            additionalProperties:
                              type: string
                        description: Resource requirements
                      nodeSelector:
                        type: object
                        additionalProperties:
                          type: string
                        description: Node selector for pod placement
                      securityContext:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        description: Pod security context
                      labels:
                        type: object
                        additionalProperties:
                          type: string
                        description: Labels for the pod
                      annotations:
                        type: object
                        additionalProperties:
                          type: string
                        description: Annotations for the pod
                  ttlSecondsAfterFinished:
                    type: integer
                    description: Time to retain completed pods
                required:
                - mainPodSpec
            required:
            - schedule
            - omJobSpec
          status:
            type: object
            properties:
              lastScheduleTime:
                type: string
                format: date-time
              lastOMJobName:
                type: string
              message:
                type: string
    additionalPrinterColumns:
    - name: Schedule
      type: string
      jsonPath: .spec.schedule
    - name: Suspended
      type: boolean
      jsonPath: .spec.suspend
    - name: Last Schedule
      type: date
      jsonPath: .status.lastScheduleTime
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: cronomjobs
    singular: cronomjob
    kind: CronOMJob
    shortNames:
    - comj