#  Copyright 2025 Collate
#  Licensed under the Collate Community License, Version 1.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/LICENSE
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
"""Render the registered OMSettings classes into a Markdown reference table."""

import importlib
from pathlib import Path
from typing import Type  # noqa: UP035

from metadata.config.settings import OMSettings, registered_settings

_HEADER = (
    "<!-- Generated by ingestion/scripts/generate_settings_docs.py — do not edit by hand. -->\n"
    "# OpenMetadata ingestion settings\n\n"
    "Every OpenMetadata-owned environment variable is `OM_`-prefixed and declared as a "
    "typed field on a registered settings class (`metadata.config.settings`).\n\n"
    "| Variable | Type | Default | Description |\n"
    "|---|---|---|---|\n"
)


def _type_name(annotation: object) -> str:
    return getattr(annotation, "__name__", str(annotation))


def render_settings_markdown(classes: dict[str, Type[OMSettings]]) -> str:  # noqa: UP006
    """Render the given settings classes as a table sorted by variable name."""
    rows = []
    for cls in classes.values():
        prefix = cls.model_config.get("env_prefix", "")
        for field_name, field in cls.model_fields.items():
            env = f"{prefix}{field_name}".upper()
            description = " ".join((field.description or "").split())
            rows.append((env, _type_name(field.annotation), repr(field.default), description))
    rows.sort()
    body = "".join(f"| `{env}` | {typ} | `{default}` | {desc} |\n" for env, typ, default, desc in rows)
    return _HEADER + body


def import_all_settings_modules() -> dict[str, Type[OMSettings]]:  # noqa: UP006
    """Import every ``settings.py`` under the metadata package; return the registry."""
    import metadata  # noqa: PLC0415

    root = Path(metadata.__file__).parent
    for path in sorted(root.rglob("settings.py")):
        parts = path.relative_to(root).with_suffix("").parts
        if "generated" in parts:
            continue
        importlib.import_module("metadata." + ".".join(parts))
    return registered_settings()
