from collections.abc import Iterable

from google.pubsub_v1.types import Schema

class SchemaServiceClient:
    def __init__(self) -> None: ...
    def get_schema(self, *, request: dict[str, str]) -> Schema: ...
    def list_schemas(self, *, request: dict[str, str]) -> Iterable[Schema]: ...
