# Copyright 2026 Collate.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ODCS Valid Example: Contract with v3.1.0 features
# Tests SLA timezone features (no schema to avoid validation issues with dynamic test tables)

apiVersion: v3.1.0
kind: DataContract
id: events-tracking-contract
name: Events Tracking Contract
version: "1.0.0"
status: active

description:
  purpose: Track user events with precise timestamps

slaProperties:
  - property: freshness
    value: "1"
    unit: hours
  - property: latency
    value: "5"
    unit: minutes
    timezone: GMT+00:00 UTC
