-- No schema change required on MySQL for this version. Intentionally statement-free.
--
-- The Postgres counterpart adds idx_profiler_data_time_series_fqnhash_pattern, a text_pattern_ops
-- index that lets the table hard-delete profiler purge (issue #27041) serve
--   entityFQNHash LIKE '<table hash>.%'
-- from an index instead of a sequential scan.
--
-- MySQL needs no equivalent. profiler_data_time_series.entityFQNHash is declared
--   VARCHAR(768) CHARACTER SET ascii COLLATE ascii_bin
-- since 1.1.5 — a binary collation — so InnoDB can already answer a LIKE prefix predicate with a
-- range scan on the leading column of the existing unique index
-- profiler_data_time_series_unique_hash_extension_ts (entityFQNHash, extension, operation,
-- timestamp). Adding a second index on the same leading column would be write overhead with no
-- read benefit.
--
-- This file exists because migrations ship one schemaChanges.sql per database per version; several
-- earlier versions (1.4.6, 1.8.4, 1.8.5, 1.10.2, 1.12.5) are statement-free on one or both dialects
-- for the same reason.
