FROM apache/airflow:2.3.3-python3.9
USER root
RUN apt-get update \
    && apt-get install -y \
        gcc libsasl2-modules libsasl2-dev build-essential libssl-dev libffi-dev librdkafka-dev \
        unixodbc-dev python3.9-dev openjdk-11-jre unixodbc freetds-dev freetds-bin \
        tdsodbc libevent-dev wget openssl libpq-dev libmysqlclient21 --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
USER airflow
# Argument to provide for Ingestion Dependencies to install. Defaults to all
ARG INGESTION_DEPENDENCY="all"
# RUN pip install --upgrade openmetadata-airflow-managed-apis openmetadata-ingestion[${INGESTION_DEPENDENCY}]
RUN pip install --extra-index-url https://test.pypi.org/simple/ openmetadata-ingestion[${INGESTION_DEPENDENCY}]==0.12.0.dev0
RUN pip install --extra-index-url https://test.pypi.org/simple/ openmetadata-managed-apis==0.12.0.dev3
RUN pip install mysqlclient
# Make and copy required folders for openmetadata-airflow-apis
RUN mkdir -p /opt/airflow/dag_generated_configs