/*
 *  Copyright 2022 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

// Import all service images
import airbyte from "../assets/services/Airbyte.png";
import airflow from "../assets/services/service-icon-airflow.png";
import alationsink from "../assets/services/service-icon-alation-sink.png";
import amazonS3 from "../assets/services/service-icon-amazon-s3.svg";
import amundsen from "../assets/services/service-icon-amundsen.png";
import athena from "../assets/services/service-icon-athena.png";
import atlas from "../assets/services/service-icon-atlas.svg";
import azuresql from "../assets/services/service-icon-azuresql.png";
import bigtable from "../assets/services/service-icon-bigtable.png";
import cassandra from "../assets/services/service-icon-cassandra.png";
import clickhouse from "../assets/services/service-icon-clickhouse.png";
import cockroach from "../assets/services/service-icon-cockroach.png";
import couchbase from "../assets/services/service-icon-couchbase.svg";
import dagster from "../assets/services/service-icon-dagster.png";
import databrick from "../assets/services/service-icon-databrick.png";
import datalake from "../assets/services/service-icon-datalake.png";
import dbt from "../assets/services/service-icon-dbt.png";
import deltalake from "../assets/services/service-icon-delta-lake.png";
import domo from "../assets/services/service-icon-domo.png";
import doris from "../assets/services/service-icon-doris.png";
import druid from "../assets/services/service-icon-druid.png";
import dynamodb from "../assets/services/service-icon-dynamodb.png";
import exasol from "../assets/services/service-icon-exasol.png";
import fivetran from "../assets/services/service-icon-fivetran.png";
import flink from "../assets/services/service-icon-flink.png";
import gcs from "../assets/services/service-icon-gcs.png";
import glue from "../assets/services/service-icon-glue.png";
import greenplum from "../assets/services/service-icon-greenplum.png";
import hive from "../assets/services/service-icon-hive.png";
import ibmdb2 from "../assets/services/service-icon-ibmdb2.png";
import iceberge from "../assets/services/service-icon-iceberg.png";
import impala from "../assets/services/service-icon-impala.png";
import kafka from "../assets/services/service-icon-kafka.png";
import kinesis from "../assets/services/service-icon-kinesis.png";
import lightDash from "../assets/services/service-icon-lightdash.png";
import looker from "../assets/services/service-icon-looker.png";
import mariadb from "../assets/services/service-icon-mariadb.png";
import metabase from "../assets/services/service-icon-metabase.png";
import microstrategy from "../assets/services/service-icon-microstrategy.svg";
import mode from "../assets/services/service-icon-mode.png";
import mongodb from "../assets/services/service-icon-mongodb.png";
import mssql from "../assets/services/service-icon-mssql.png";
import nifi from "../assets/services/service-icon-nifi.png";
import openlineage from "../assets/services/service-icon-openlineage.svg";
import oracle from "../assets/services/service-icon-oracle.png";
import pinot from "../assets/services/service-icon-pinot.png";
import postgres from "../assets/services/service-icon-post.png";
import powerbi from "../assets/services/service-icon-power-bi.png";
import presto from "../assets/services/service-icon-presto.png";
import qlikSense from "../assets/services/service-icon-qlik-sense.png";
import query from "../assets/services/service-icon-query.png";
import quicksight from "../assets/services/service-icon-quicksight.png";
import redash from "../assets/services/service-icon-redash.png";
import redpanda from "../assets/services/service-icon-redpanda.png";
import redshift from "../assets/services/service-icon-redshift.png";
import sagemaker from "../assets/services/service-icon-sagemaker.png";
import salesforce from "../assets/services/service-icon-salesforce.png";
import sapErp from "../assets/services/service-icon-sap-erp.png";
import sapHana from "../assets/services/service-icon-sap-hana.png";
import sas from "../assets/services/service-icon-sas.svg";
import scikit from "../assets/services/service-icon-scikit.png";
import sigma from "../assets/services/service-icon-sigma.png";
import singlestore from "../assets/services/service-icon-singlestore.png";
import snowflakes from "../assets/services/service-icon-snowflakes.png";
import spark from "../assets/services/service-icon-spark.png";
import spline from "../assets/services/service-icon-spline.png";
import mysql from "../assets/services/service-icon-sql.png";
import sqlite from "../assets/services/service-icon-sqlite.png";
import superset from "../assets/services/service-icon-superset.png";
import synapse from "../assets/services/service-icon-synapse.png";
import tableau from "../assets/services/service-icon-tableau.png";
import trino from "../assets/services/service-icon-trino.png";
import unitycatalog from "../assets/services/service-icon-unitycatalog.svg";
import vertica from "../assets/services/service-icon-vertica.png";

// Import default service icons
import dashboardDefault from "../assets/services/dashboard.svg";
import iconDefaultService from "../assets/services/default-service-icon.svg";
import elasticSearch from "../assets/services/elasticsearch.svg";
import databaseDefault from "../assets/services/ic-custom-database.svg";
import mlModelDefault from "../assets/services/ic-custom-model.svg";
import searchDefault from "../assets/services/ic-custom-search.svg";
import storageDefault from "../assets/services/ic-custom-storage.svg";
import restService from "../assets/services/ic-service-rest-api.svg";
import logo from "../assets/services/logo-monogram.svg";
import openSearch from "../assets/services/open-search.svg";
import pipelineDefault from "../assets/services/pipeline.svg";
import mlflow from "../assets/services/service-icon-mlflow.svg";
import teradata from "../assets/services/teradata.svg";
import topicDefault from "../assets/services/topic.svg";

// Export all service constants
export const MYSQL = mysql;
export const SQLITE = sqlite;
export const MSSQL = mssql;
export const REDSHIFT = redshift;
export const BIGQUERY = query;
export const BIGTABLE = bigtable;
export const HIVE = hive;
export const IMPALA = impala;
export const POSTGRES = postgres;
export const ORACLE = oracle;
export const SNOWFLAKE = snowflakes;
export const ATHENA = athena;
export const PRESTO = presto;
export const TRINO = trino;
export const GLUE = glue;
export const MARIADB = mariadb;
export const VERTICA = vertica;
export const KAFKA = kafka;
export const REDPANDA = redpanda;
export const SUPERSET = superset;
export const SYNAPSE = synapse;
export const LOOKER = looker;
export const MICROSTRATEGY = microstrategy;
export const TABLEAU = tableau;
export const REDASH = redash;
export const METABASE = metabase;
export const AZURESQL = azuresql;
export const CLICKHOUSE = clickhouse;
export const DATABRICK = databrick;
export const UNITYCATALOG = unitycatalog;
export const IBMDB2 = ibmdb2;
export const DORIS = doris;
export const DRUID = druid;
export const DYNAMODB = dynamodb;
export const SIGMA = sigma;
export const SINGLESTORE = singlestore;
export const SALESFORCE = salesforce;
export const MLFLOW = mlflow;
export const SAP_HANA = sapHana;
export const SAP_ERP = sapErp;
export const SCIKIT = scikit;
export const DELTALAKE = deltalake;
export const DEFAULT_SERVICE = iconDefaultService;
export const AIRBYTE = airbyte;
export const PINOT = pinot;
export const DATALAKE = datalake;
export const MODE = mode;
export const DAGSTER = dagster;
export const DBT = dbt;
export const FIVETRAN = fivetran;
export const AMUNDSEN = amundsen;
export const ATLAS = atlas;
export const ALATIONSINK = alationsink;
export const SAS = sas;
export const OPENLINEAGE = openlineage;
export const LOGO = logo;
export const EXASOL = exasol;
export const AIRFLOW = airflow;
export const POWERBI = powerbi;
export const DATABASE_DEFAULT = databaseDefault;
export const TOPIC_DEFAULT = topicDefault;
export const DASHBOARD_DEFAULT = dashboardDefault;
export const PIPELINE_DEFAULT = pipelineDefault;
export const ML_MODEL_DEFAULT = mlModelDefault;
export const CUSTOM_STORAGE_DEFAULT = storageDefault;
export const NIFI = nifi;
export const KINESIS = kinesis;
export const QUICKSIGHT = quicksight;
export const DOMO = domo;
export const SAGEMAKER = sagemaker;
export const AMAZON_S3 = amazonS3;
export const GCS = gcs;
export const SPARK = spark;
export const SPLINE = spline;
export const MONGODB = mongodb;
export const CASSANDRA = cassandra;
export const COCKROACH = cockroach;
export const COUCHBASE = couchbase;
export const FLINK = flink;
export const GREENPLUM = greenplum;
export const ICEBERGE = iceberge;
export const TERADATA = teradata;
export const QLIK_SENSE = qlikSense;
export const CUSTOM_SEARCH_DEFAULT = searchDefault;
export const ELASTIC_SEARCH = elasticSearch;
export const OPEN_SEARCH = openSearch;
export const REST_SERVICE = restService;
export const LIGHT_DASH = lightDash;
