#!/usr/bin/env sh
# .husky/pre-commit
# ...
cd openmetadata-ui/src/main/resources/ui
yarn pre-commit


changed_files=$(git diff --cached --name-only --diff-filter=ACM | grep 'openmetadata-spec/src/main/resources/json/schema/')

if [ -n "$changed_files" ]; then
    echo "JSON schema files changed. Regenerating TypeScript files..."
    ./json2ts.sh $changed_files
    git add openmetadata-ui/src/main/resources/ui/src/generated
else
    echo "No changes in JSON schema files. Skipping TypeScript generation."
fi
