#!/usr/bin/env sh
# .husky/pre-commit
# ...

# this should run first before running the yarn pre-commit hook as we are changing the directory
changed_files=$(git diff --cached --name-only --diff-filter=ACM | grep 'openmetadata-spec/src/main/resources/json/schema/')

if [ -n "$changed_files" ]; then
    echo "JSON schema files changed. Regenerating TypeScript files..."
    ./openmetadata-ui/src/main/resources/ui/json2ts.sh $changed_files
    git add openmetadata-ui/src/main/resources/ui/src/generated
else
    echo "No changes in JSON schema files. Skipping TypeScript generation."
fi

cd openmetadata-ui/src/main/resources/ui
yarn generate:app-docs
yarn pre-commit
