/*
 *  Copyright 2025 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * SVGR index template — generates src/icons/index.ts.
 */
const path = require('path');

const template = (files) => {
  const exports = files
    .map((file) => {
      const name = path.basename(file, path.extname(file));
      return `export { ${name} } from './${name}'`;
    })
    .join('\n');

  return `/*
 *  Copyright 2025 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

// This file is auto-generated by scripts/generate-icons.mjs — do not edit manually.
// Run \`yarn icons:generate\` to regenerate after adding SVGs to src/icons/raw/.

export type { IconProps } from './types';
${exports}
`;
};

module.exports = template;
