package org.openmetadata.service.jdbi3;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Set;
import org.junit.jupiter.api.Test;
import org.openmetadata.service.Entity;
import org.openmetadata.service.util.EntityUtil;

/**
 * Tests that field names generated by {@link EntityUtil#getFieldName(String...)} are compatible with
 * the {@code shouldCompare} patchedFields matching logic.
 *
 * <p>This test exists because PR #25751 introduced a {@code shouldCompare} optimization that skips
 * field comparisons when the field name doesn't match the patchedFields extracted from the JSON
 * patch path. Entities with wrapper objects (e.g., Topic's messageSchema wrapping schemaFields,
 * Container's dataModel wrapping columns) are vulnerable to mismatches when field names are built
 * without the wrapper prefix.
 */
class ShouldCompareFieldNamesTest {

  /**
   * Simulates the shouldCompare logic from EntityRepository.EntityUpdater. This is extracted here
   * so we can test field name patterns without needing a full EntityUpdater instance.
   */
  private boolean shouldCompare(Set<String> patchedFields, String fieldName) {
    if (patchedFields == null || fieldName == null) {
      return true;
    }
    if (patchedFields.contains(fieldName)) {
      return true;
    }
    int fieldPathSeparator = fieldName.indexOf(Entity.SEPARATOR);
    if (fieldPathSeparator > 0
        && patchedFields.contains(fieldName.substring(0, fieldPathSeparator))) {
      return true;
    }
    for (String patchedField : patchedFields) {
      if (fieldName.startsWith(patchedField + Entity.SEPARATOR)
          || patchedField.startsWith(fieldName + Entity.SEPARATOR)) {
        return true;
      }
    }
    return false;
  }

  // ===================================================================
  // Table: columns is top-level → patchedField = "columns"
  // ===================================================================

  @Test
  void table_columnDescription_matchesColumnsPatched() {
    Set<String> patched = Set.of("columns");
    String field = EntityUtil.getFieldName("columns", "user_id", "description");
    assertTrue(shouldCompare(patched, field), "columns.user_id.description should match 'columns'");
  }

  @Test
  void table_columnTags_matchesColumnsPatched() {
    Set<String> patched = Set.of("columns");
    String field = EntityUtil.getFieldName("columns", "user_id", "tags");
    assertTrue(shouldCompare(patched, field), "columns.user_id.tags should match 'columns'");
  }

  @Test
  void table_columnDisplayName_matchesColumnsPatched() {
    Set<String> patched = Set.of("columns");
    String field = EntityUtil.getFieldName("columns", "user_id", "displayName");
    assertTrue(shouldCompare(patched, field), "columns.user_id.displayName should match 'columns'");
  }

  // ===================================================================
  // Container: dataModel wraps columns → patchedField = "dataModel"
  // ===================================================================

  @Test
  void container_columnDescription_matchesDataModelPatched() {
    Set<String> patched = Set.of("dataModel");
    String field = EntityUtil.getFieldName("dataModel.columns", "user_id", "description");
    assertTrue(
        shouldCompare(patched, field),
        "dataModel.columns.user_id.description should match 'dataModel'");
  }

  @Test
  void container_columnTags_matchesDataModelPatched() {
    Set<String> patched = Set.of("dataModel");
    String field = EntityUtil.getFieldName("dataModel.columns", "user_id", "tags");
    assertTrue(
        shouldCompare(patched, field), "dataModel.columns.user_id.tags should match 'dataModel'");
  }

  @Test
  void container_columnDisplayName_matchesDataModelPatched() {
    Set<String> patched = Set.of("dataModel");
    String field = EntityUtil.getFieldName("dataModel.columns", "user_id", "displayName");
    assertTrue(
        shouldCompare(patched, field),
        "dataModel.columns.user_id.displayName should match 'dataModel'");
  }

  @Test
  void container_columnConstraint_matchesDataModelPatched() {
    Set<String> patched = Set.of("dataModel");
    String field = EntityUtil.getFieldName("dataModel.columns", "user_id", "constraint");
    assertTrue(
        shouldCompare(patched, field),
        "dataModel.columns.user_id.constraint should match 'dataModel'");
  }

  // ===================================================================
  // Topic: messageSchema wraps schemaFields → patchedField = "messageSchema"
  // ===================================================================

  @Test
  void topic_schemaFieldDescription_matchesMessageSchemaPatched() {
    Set<String> patched = Set.of("messageSchema");
    String field = EntityUtil.getFieldName("messageSchema.schemaFields", "user_id", "description");
    assertTrue(
        shouldCompare(patched, field),
        "messageSchema.schemaFields.user_id.description should match 'messageSchema'");
  }

  @Test
  void topic_schemaFieldTags_matchesMessageSchemaPatched() {
    Set<String> patched = Set.of("messageSchema");
    String field = EntityUtil.getFieldName("messageSchema.schemaFields", "user_id", "tags");
    assertTrue(
        shouldCompare(patched, field),
        "messageSchema.schemaFields.user_id.tags should match 'messageSchema'");
  }

  @Test
  void topic_schemaFieldDisplayName_matchesMessageSchemaPatched() {
    Set<String> patched = Set.of("messageSchema");
    String field = EntityUtil.getFieldName("messageSchema.schemaFields", "user_id", "displayName");
    assertTrue(
        shouldCompare(patched, field),
        "messageSchema.schemaFields.user_id.displayName should match 'messageSchema'");
  }

  // ===================================================================
  // APIEndpoint: requestSchema/responseSchema wrap schemaFields
  // ===================================================================

  @Test
  void apiEndpoint_requestSchemaFieldDescription_matchesRequestSchemaPatched() {
    Set<String> patched = Set.of("requestSchema");
    String field = EntityUtil.getFieldName("requestSchema.schemaFields", "body", "description");
    assertTrue(
        shouldCompare(patched, field),
        "requestSchema.schemaFields.body.description should match 'requestSchema'");
  }

  @Test
  void apiEndpoint_responseSchemaFieldTags_matchesResponseSchemaPatched() {
    Set<String> patched = Set.of("responseSchema");
    String field = EntityUtil.getFieldName("responseSchema.schemaFields", "status", "tags");
    assertTrue(
        shouldCompare(patched, field),
        "responseSchema.schemaFields.status.tags should match 'responseSchema'");
  }

  // ===================================================================
  // SearchIndex: fields is top-level → patchedField = "fields"
  // ===================================================================

  @Test
  void searchIndex_fieldDescription_matchesFieldsPatched() {
    Set<String> patched = Set.of("fields");
    String field = EntityUtil.getFieldName("fields", "title", "description");
    assertTrue(shouldCompare(patched, field), "fields.title.description should match 'fields'");
  }

  @Test
  void searchIndex_fieldTags_matchesFieldsPatched() {
    Set<String> patched = Set.of("fields");
    String field = EntityUtil.getFieldName("fields", "title", "tags");
    assertTrue(shouldCompare(patched, field), "fields.title.tags should match 'fields'");
  }

  // ===================================================================
  // Nested children: verify deeply nested fields still match
  // ===================================================================

  @Test
  void topic_nestedChildDescription_matchesMessageSchemaPatched() {
    Set<String> patched = Set.of("messageSchema");
    // Simulates: messageSchema.schemaFields → parent field → child field → description
    String field =
        EntityUtil.getFieldName("messageSchema.schemaFields.record", "name", "description");
    assertTrue(
        shouldCompare(patched, field),
        "Deeply nested child field description should match 'messageSchema'");
  }

  @Test
  void container_nestedChildDisplayName_matchesDataModelPatched() {
    Set<String> patched = Set.of("dataModel");
    String field = EntityUtil.getFieldName("dataModel.columns.address", "street", "displayName");
    assertTrue(
        shouldCompare(patched, field),
        "Deeply nested child column displayName should match 'dataModel'");
  }
}
