apiVersion: v1
kind: ServiceAccount
metadata:
  name: om-argo-sa
  namespace: openmetadata
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: om-argo-role
  namespace: openmetadata
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "get", "list", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtemplates", "workflowtasksets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: om-argo-rolebinding
  namespace: openmetadata
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: om-argo-role
subjects:
- kind: ServiceAccount
  name: om-argo-sa
  namespace: openmetadata