from collections.abc import Iterable, Iterator
from typing import Any

from google.auth.credentials import Credentials

class Client:
    project: str | None
    def __init__(
        self,
        project: str | None = None,
        credentials: Credentials | None = None,
        **kwargs: Any,
    ) -> None: ...
    def bucket(self, bucket_name: str) -> Bucket: ...
    def get_bucket(self, bucket_or_name: str | Bucket) -> Bucket: ...
    def list_buckets(self, **kwargs: Any) -> Iterable[Bucket]: ...
    def list_blobs(self, bucket_or_name: str | Bucket, **kwargs: Any) -> Iterator[Blob]: ...

class Bucket:
    name: str
    def blob(self, blob_name: str) -> Blob: ...
    def get_blob(self, blob_name: str, **kwargs: Any) -> Blob | None: ...
    def list_blobs(self, prefix: str | None = None, **kwargs: Any) -> Iterator[Blob]: ...

class Blob:
    name: str
    size: int | None
    def download_as_bytes(self, **kwargs: Any) -> bytes: ...
    def download_as_string(self, **kwargs: Any) -> bytes: ...
