/*
 *  Copyright 2026 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

export const LONG_DESCRIPTION_END_TEXT =
  'Access is managed through role-based permissions';

const LONG_DESCRIPTION_LINES = [
  '# Overview',
  '',
  'This is a comprehensive description that spans multiple paragraphs and sections.',
  'It contains detailed information about the entity to test scroll and visibility behavior.',
  'The purpose of this document is to provide enough content to push the lower sections',
  'well below the visible viewport area so that scrolling is required to reach them.',
  '',
  '## Key Features',
  '',
  '- Feature one: Provides data ingestion capabilities from various sources including databases, APIs, and file systems',
  '- Feature two: Supports multiple data source connectors and integrations with third-party tools',
  '- Feature three: Enables real-time data processing and streaming with low latency guarantees',
  '- Feature four: Offers comprehensive monitoring and alerting for pipeline health and data quality',
  '- Feature five: Includes automated data quality checks and validations at every stage',
  '- Feature six: Provides detailed lineage tracking across all data transformations',
  '- Feature seven: Supports role-based access control for fine-grained security',
  '- Feature eight: Enables automated metadata extraction and classification',
  '- Feature nine: Provides comprehensive audit logging for compliance requirements',
  '- Feature ten: Supports custom metadata annotations and tagging workflows',
  '',
  '## Technical Details',
  '',
  'The system processes data through a multi-stage pipeline that includes',
  'extraction, transformation, and loading phases. Each phase is carefully',
  'monitored and validated to ensure data integrity and consistency.',
  'The pipeline supports both batch and streaming modes of operation.',
  '',
  '### Architecture',
  '',
  'The architecture follows a microservices pattern with dedicated services',
  'for each processing stage. Communication between services uses event-driven',
  'messaging patterns for reliable data delivery. The system is designed to',
  'scale horizontally to handle increasing data volumes.',
  '',
  '### Data Model',
  '',
  '| Column | Type | Description |',
  '|--------|------|-------------|',
  '| id | UUID | Primary identifier for each record |',
  '| name | VARCHAR(255) | Human-readable entity name |',
  '| description | TEXT | Detailed description of the entity |',
  '| created_at | TIMESTAMP | Record creation timestamp |',
  '| updated_at | TIMESTAMP | Last modification timestamp |',
  '| created_by | VARCHAR(255) | User who created the record |',
  '| status | ENUM | Current status of the entity |',
  '| version | FLOAT | Schema version number |',
  '',
  '## Integration Points',
  '',
  'The system integrates with multiple external services and platforms:',
  '',
  '### Database Connectors',
  '',
  'Supported databases include PostgreSQL, MySQL, Oracle, SQL Server,',
  'Snowflake, BigQuery, Redshift, and Databricks. Each connector provides',
  'full metadata extraction including schemas, tables, columns, and relationships.',
  '',
  '### API Integrations',
  '',
  'RESTful APIs are available for all major operations. The API supports',
  'pagination, filtering, and sorting. Authentication uses JWT tokens',
  'with configurable expiration and refresh mechanisms.',
  '',
  '### Event System',
  '',
  'The event system publishes notifications for all metadata changes.',
  'Consumers can subscribe to specific entity types or change types.',
  'Events are delivered with at-least-once semantics and include',
  'full change details for downstream processing.',
  '',
  '## Operational Guidelines',
  '',
  'This section covers the operational procedures and best practices',
  'for managing and maintaining the system in production environments.',
  '',
  '### Deployment',
  '',
  'The system supports containerized deployment using Docker and Kubernetes.',
  'Helm charts are provided for standard deployment configurations.',
  'Rolling updates ensure zero-downtime deployments.',
  '',
  '### Monitoring',
  '',
  'Key metrics are exposed via Prometheus endpoints. Pre-built Grafana',
  'dashboards provide visibility into pipeline health, throughput,',
  'error rates, and resource utilization.',
  '',
  '### Backup and Recovery',
  '',
  'Automated daily backups are configured by default. Point-in-time',
  'recovery is supported for the metadata database. Backup retention',
  'policy is configurable based on organizational requirements.',
  '',
  '## Usage Guidelines',
  '',
  'Users should follow the documented procedures when modifying this entity.',
  'All changes must go through the standard review process before deployment.',
  'Documentation must be updated alongside any structural changes.',
  '',
  '### Access Control',
  '',
  `${LONG_DESCRIPTION_END_TEXT}. Contact the data team`,
  'for access requests. Review cycles occur on a weekly basis.',
];

export const LONG_DESCRIPTION = LONG_DESCRIPTION_LINES.join('\n');
