-- Index the FQN-hash prefix scan behind the table hard-delete profiler purge (issue #27041).
--
-- TableRepository.entitySpecificCleanup purges a hard-deleted table's column profiles with
-- EntityTimeSeriesDAO.deleteDescendants, which matches
--   entityFQNHash LIKE '<table hash>.%'
-- because column profiles are keyed by the *column* FQN, not the table FQN. The only persistent
-- index with entityFQNHash leading is the 1.1.5 unique constraint
-- (entityFQNHash, extension, operation, timestamp); it uses the default operator class and the
-- column inherits the database default collation (en_US.UTF-8 on managed Postgres / RDS), neither
-- of which qualifies the planner to use it for LIKE 'prefix%'. The 1.9.9 migration did create
-- idx_pdts_entityFQNHash_prefix, but that was a migration-time helper and the same script drops it
-- again, so nothing persistent covers this predicate today.
--
-- Without this index every table hard delete costs at least one sequential scan of
-- profiler_data_time_series, and a recursive service delete costs one per table. Measured on
-- postgres:15 (lc_collate=en_US.utf8) with 300k rows / 211 MB, using the exact statement the DAO
-- issues (JDBC binds the prefix as text):
--   before: Parallel Seq Scan, 24.174 ms, 11112 buffers   (terminal batch, prefix matches nothing)
--   after : Index Scan,         0.056 ms,     3 buffers
--   before: Seq Scan,          16.579 ms,  3701 buffers   (first batch, prefix matches 3000 rows)
--   after : Bitmap Heap Scan,   8.647 ms,  1006 buffers
-- Index size 2776 kB against a 211 MB table.
--
-- Why text_pattern_ops and not varchar_pattern_ops:
-- entityFQNHash is VARCHAR(768), so varchar_pattern_ops is the type-matched choice on paper. In
-- practice the planner normalises `varchar LIKE text` — which is what every JDBC setString bind
-- produces — by casting the column, giving `(entityfqnhash)::text ~~ ...`. text_pattern_ops matches
-- that cast expression on every version; the 1.13.0 fqnHash pass documents an environment where
-- varchar_pattern_ops was silently unused and the table seq-scanned. This file follows the same
-- opclass as the idx_*_fqnhash_pattern family for that reason.
--
-- Built CONCURRENTLY so the migration takes no write lock, matching the 1.11.0 idx_tag_usage_* and
-- 1.13.0 idx_*_fqnhash_pattern pattern. Each statement runs outside an implicit transaction, which
-- the native migration runner supports.
--
-- OPERATOR RUNBOOK — interrupted CONCURRENTLY builds.
-- An interrupted CREATE INDEX CONCURRENTLY leaves an INVALID index behind, and `IF NOT EXISTS`
-- would then no-op against it forever. Detect and remediate:
--   SELECT c.relname FROM pg_class c
--    JOIN pg_index i ON i.indexrelid = c.oid
--    WHERE NOT i.indisvalid
--      AND c.relname = 'idx_profiler_data_time_series_fqnhash_pattern';
--   DROP INDEX CONCURRENTLY idx_profiler_data_time_series_fqnhash_pattern;
--   DELETE FROM server_migration_sql_logs
--    WHERE version = '2.1.1'
--      AND sqlstatement LIKE '%idx\_profiler\_data\_time\_series\_fqnhash\_pattern%' ESCAPE '\';
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_profiler_data_time_series_fqnhash_pattern
    ON profiler_data_time_series (entityFQNHash text_pattern_ops);
