/*
 *  Copyright 2024 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

export enum EntityType {
  TABLE = 'table',
  TABLE_COLUMN = 'tableColumn',
  TOPIC = 'topic',
  CLASSIFICATION = 'classification',
  DASHBOARD = 'dashboard',
  PIPELINE = 'pipeline',
  DATABASE = 'database',
  DATABASE_SCHEMA = 'databaseSchema',
  GLOSSARY = 'glossary',
  GLOSSARY_TERM = 'glossaryTerm',
  DATABASE_SERVICE = 'databaseService',
  MESSAGING_SERVICE = 'messagingService',
  METADATA_SERVICE = 'metadataService',
  DASHBOARD_SERVICE = 'dashboardService',
  PIPELINE_SERVICE = 'pipelineService',
  MLMODEL_SERVICE = 'mlmodelService',
  STORAGE_SERVICE = 'storageService',
  SEARCH_SERVICE = 'searchService',
  SECURITY_SERVICE = 'securityService',
  DRIVE_SERVICE = 'driveService',
  WEBHOOK = 'webhook',
  MLMODEL = 'mlmodel',
  TYPE = 'type',
  TEAM = 'team',
  USER = 'user',
  BOT = 'bot',
  ROLE = 'role',
  POLICY = 'policy',
  TEST_SUITE = 'testSuite',
  TEST_CASE = 'testCase',
  DATA_INSIGHT_CHART = 'dataInsightChart',
  KPI = 'kpi',
  ALERT = 'alert',
  CONTAINER = 'container',
  TAG = 'tag',
  DASHBOARD_DATA_MODEL = 'dashboardDataModel',
  SUBSCRIPTION = 'subscription',
  CHART = 'chart',
  DOMAIN = 'domain',
  DATA_PRODUCT = 'dataProduct',
  SAMPLE_DATA = 'sampleData',
  STORED_PROCEDURE = 'storedProcedure',
  SEARCH_INDEX = 'searchIndex',
  APP_MARKET_PLACE_DEFINITION = 'appMarketPlaceDefinition',
  APPLICATION = 'app',
  PERSONA = 'persona',
  DOC_STORE = 'docStore',
  PAGE = 'Page',
  KNOWLEDGE_PAGE = 'page',
  knowledgePanels = 'KnowLedgePanels',
  GOVERN = 'govern',
  ALL = 'all',
  CUSTOM_METRIC = 'customMetric',
  INGESTION_PIPELINE = 'ingestionPipeline',
  QUERY = 'query',
  ENTITY_REPORT_DATA = 'entityReportData',
  WEB_ANALYTIC_ENTITY_VIEW_REPORT_DATA = 'webAnalyticEntityViewReportData',
  WEB_ANALYTIC_USER_ACTIVITY_REPORT_DATA = 'webAnalyticUserActivityReportData',
  TEST_CASE_RESOLUTION_STATUS = 'test_case_resolution_status_search_index',
  TEST_CASE_RESULT = 'test_case_result_search_index',
  EVENT_SUBSCRIPTION = 'eventsubscription',
  LINEAGE_EDGE = 'lineageEdge',
  API_SERVICE = 'apiService',
  API_COLLECTION = 'apiCollection',
  API_ENDPOINT = 'apiEndpoint',
  METRIC = 'metric',
  WORKFLOW_DEFINITION = 'workflowDefinition',
  SERVICE = 'service',
  DATA_CONTRACT = 'dataContract',
  INGESTION_RUNNER = 'ingestionRunner',
  DIRECTORY = 'directory',
  FILE = 'file',
  SPREADSHEET = 'spreadsheet',
  WORKSHEET = 'worksheet',
  NOTIFICATION_TEMPLATE = 'notificationTemplate',
}
