/*
 *  Copyright 2026 Collate.
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
import { test as setup } from '@playwright/test';
import { performAdminLogin } from '../utils/admin';

/**
 * Lowers the ActivityFeedAlert subscription poll interval for the test run only.
 *
 * The activity feed is delivered by a single offset-ordered consumer whose default
 * cadence (pollInterval 30s) cannot drain the change-event volume generated by the
 * parallel suite, so activity rows arrive after the e2e poll window and the
 * "Activity API - Entity Changes" tests time out. Shrinking the interval raises the
 * drain rate enough to keep the backlog shallow.
 *
 * This only patches the running test deployment (production never runs Playwright),
 * and the change is applied via the supported subscription API, which reschedules
 * the consumer live without losing its offset.
 */
const SUBSCRIPTION_NAME = 'ActivityFeedAlert';
const POLL_INTERVAL = Number(process.env.ACTIVITY_FEED_POLL_INTERVAL ?? 10);
const JSON_PATCH_CONTENT_TYPE = 'application/json-patch+json';

setup(
  'boost ActivityFeedAlert consumer throughput for tests',
  async ({ browser }) => {
    // Only the ephemeral CI deployment needs this; never mutate a persistent
    // local dev environment.
    if (!process.env.CI) {
      return;
    }

    const { apiContext, afterAction } = await performAdminLogin(browser);

    try {
      const subscriptionResponse = await apiContext.get(
        `/api/v1/events/subscriptions/name/${SUBSCRIPTION_NAME}`
      );

      if (!subscriptionResponse.ok()) {
        return;
      }

      const subscription = await subscriptionResponse.json();

      const patchResponse = await apiContext.patch(
        `/api/v1/events/subscriptions/${subscription.id}`,
        {
          data: [
            { op: 'replace', path: '/pollInterval', value: POLL_INTERVAL },
          ],
          headers: { 'Content-Type': JSON_PATCH_CONTENT_TYPE },
        }
      );

      // Best-effort: this setup gates the whole `chromium` project, so a failed boost must
      // not skip every test. Log loudly and continue; the worst case is renewed ActivityAPI
      // flakiness, scoped to those tests.
      if (!patchResponse.ok()) {
        console.error(
          `[activity-config] Could not boost ActivityFeedAlert pollInterval (HTTP ${patchResponse.status()})`
        );
      }
    } finally {
      await afterAction();
    }
  }
);
