name: Phylum Analyze
on:
    workflow_dispatch:
    push:
        branches:
        - main
        - '0.[0-9]+.[0-9]+'
        paths-ignore:
        - 'openmetadata-docs/**'
        - 'openmetadata-docs-v1/**'
    pull_request_target:
        types: [labeled, opened, synchronize, reopened]
        paths:
        - "ingestion/**"
        - "openmetadata-service/**"
        - "openmetadata-ui/**"
jobs:
  analyze_deps:
    name: Analyze dependencies with Phylum
    environment: test
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Analyze dependencies
        uses: phylum-dev/phylum-analyze-pr-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          phylum_token: ${{ secrets.PHYLUM_TOKEN }}
          cmd: |
            phylum-ci -vv \
            --depfile ingestion/setup.py \
            --depfile ingestion/pyproject.toml \
            --depfile openmetadata-service/pom.xml \
            --depfile openmetadata-ui/src/main/resources/ui/yarn.lock
