#  Copyright 2021 Collate
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#  http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Selenium No Ingestion Java CI

on:
  pull_request:
    branches:
      - main
      - '0.[0-9]+.[0-9]+'
    paths:
      - 'openmetadata-ui/src/main/resources/ui/**'
      - 'openmetadata-ui/src/test/java/org/openmetadata/catalog/selenium/pagesWithoutData/**'

permissions:
  contents: read

concurrency: 
  group: selenium-noIngestion-tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true      
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generating Data Models
      run: |
        sudo make install_antlr_cli
        make install_dev generate

    - name: Maven Package
      run: mvn -DskipTests clean package

    - name: Start Server
      run: cd ./docker/development && docker-compose up -d openmetadata-server mysql elasticsearch
      timeout-minutes: 20

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Run Page Tests without data
      run: mvn clean test -Dtest="org.openmetadata.catalog.selenium.pagesWithoutData.**.*.java" -DfailIfNoTests=false

