apiVersion: pipelines.openmetadata.org/v1
kind: CronOMJob
metadata:
  name: sample-cronomjob
  namespace: openmetadata-pipelines
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  timeZone: "UTC"
  suspend: false
  startingDeadlineSeconds: 300  # 5 minutes deadline
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  omJobSpec:
    mainPodSpec:
      image: openmetadata/ingestion:latest
      imagePullPolicy: IfNotPresent
      command: 
        - "python"
        - "main.py"
        - "run"
      env:
        - name: PIPELINE_TYPE
          value: "metadata"
        - name: CONFIG
          valueFrom:
            configMapKeyRef:
              name: pipeline-config
              key: config
      serviceAccountName: openmetadata-ingestion
      resources:
        requests:
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
    exitHandlerSpec:
      image: openmetadata/ingestion:latest
      imagePullPolicy: IfNotPresent
      command:
        - "python"
        - "/opt/openmetadata/ingestion/exit_handler.py"
      env:
        - name: PIPELINE_TYPE
          value: "metadata"
        - name: PIPELINE_RUN_ID
          value: "scheduled"
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "250m"
          memory: "512Mi"
    ttlSecondsAfterFinished: 3600  # Clean up after 1 hour